spring:
  profiles:
    active: dev
  cache:
    redis:
      use-key-prefix: true
      key-prefix: "nt:"
  servlet:
      multipart:
        max-file-size: 500MB
        max-request-size: 500MB
mybatis-plus:
  mapper-locations: classpath*:com/haoyu/**/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: flag
      logic-delete-value: Y
      logic-not-delete-value: N
    super-mapper-class: com.haoyu.framework.core.base.BaseMapper
logging:
  config: classpath:log4j2.xml
auth:
  config:
    ignores:
      get:
        - "/cms/api/v1/**"
        - "/api/v1/auth/captcha"
      # 不需要过滤的 post 请求
      post:
        - "/cms/api/v1/file/fileInfo/download/byUrl"
        - "/api/v1/auth/login"
        - "/api/v1/auth/logout"
        - "/cms/api/v1/file/upload/temp/**"
        - "/cms/api/v1/user/userProfessional/**"
        - "/cms/api/v1/community/visit/**"
        - "/api/v1/services/**"
      # 不需要过滤的请求，不限方法
      pattern:
        - "/cms/api/v1/user/**"
        - "/api/v1/file/fileInfo/download/*"
        - "/test/*"
        # //前端的
        - "/favicon.ico"
        # //swagger相关的
        - "/swagger-ui.html"
        - "/doc.html"
        - "/webjars/**"
        - "/swagger-resources/**"
        - "/v2/api-docs"
        - "/v2/api-docs-ext"
        - "/configuration/ui"
        - "/configuration/security"
        # //后端的
        - "/"
        - "/login"
        - "/logout"
        # //文件的
        - "/sysFileInfo/upload"
        - "/sysFileInfo/download"
        - "/sysFileInfo/preview"
        # //druid的
        - "/druid/**"
        # //手机端的登录
        - "/courseSign/login"
      xss:
        - "/druid/**"
server:
  max-http-header-size: 81920
